### ISSUE TITLE
JSON dump of tweets has text truncation

### ISSUE THREAD

**Issue by joannac-** [rtyler/brokenco.de#5]
The @sadserver json blob (and presumably sadoperator as well) seems to have truncation. e.g. the first tweet in the blob has
```
  "full_text" : "RT @mutablejoe: He's making a list\nHe's checking it twice\nHe's gonna find out who's naughty or nice\nSanta Claus is in contravention of arti…",
```
It's not clear why... there are longer tweets shown without truncation
```
  "full_text" : "PIDs like the cryptominers' can often sensationalize CPU and spread unsubstantiated load, so it’s critical the kernel document, validate, and refute such scheduling priorities directly so processes can form their own opinions. This is what serves the production runtime best.",
```

Would it be possible to get an updated blob without truncation?

**Comment by rtyler** [comment]
That's weird, this is a direct dump from twitter. I'll take a poke at it later

**Comment by rtyler** [comment]
I doubt I'll get to this at any point. I haven't logged into those accounts basically since the retiring. Might be easier to just scrape Twitter :facepalm:
